server:
  port: 8090

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

spring:
  cloud:
    gateway:
      routes:
        - id: tarifa-reserva
          uri: lb://TARIFA-RESERVA
          predicates:
            - Path=/tarifa-reserva/**
          filters:
            - StripPrefix=1
      globalcors:
        cors-configurations:
          "[/**]":
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
