server:
  port: 8090

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

spring:
  cloud:
    gateway:
      routes:
        - id: tarifa-reserva
          uri: lb://tarifa-reserva
          predicates:
            - Path=/api/tarifas/**
      globalcors:
        cors-configurations:
          "[/**]":
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.web.reactive: DEBUG
    reactor.netty: DEBUG