server:
  port: 8090
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server-service:8761/eureka/
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          "[/**]":
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        # M1
        - id: tarifa-reserva
          uri: lb://tarifa-reserva
          predicates:
            - Path=/api/reservas/**
            - Path=/api/tarifas/**
        # M2
        - id: dcto-personas
          uri: lb://dcto-personas
          predicates:
            - Path=/api/dcto-personas/**
        # M3
        - id: dcto-frecuente
          uri: lb://dcto-frecuente
          predicates:
            - Path=/api/dcto-frecuente/**
        # M4
        - id: tarifas-especiales
          uri: lb://tarifas-especiales
          predicates:
            - Path=/api/tarifas-especiales/**
        # M5
        - id: registro-comprobantes
          uri: lb://registro-comprobantes
          predicates:
            - Path=/api/comprobantes/**
            - Path=/api/reservas/**
        # M6
        - id: rack-semanal
          uri: lb://rack-semanal
          predicates:
            - Path=/api/rack-semanal/**
        # M7
        - id: reportes
          uri: lb://reportes
          predicates:
            - Path=/api/reportes/**
