server:
  port: 8097
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/reportes_db
    username: postgres
    password: Admin
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka


        #spring:
  #application:
    #name: reportes
  #config:
    #import: optional:configserver:http://localhost:8888

#server:
  #port: 0

#eureka:
  #client:
    #service-url:
      #defaultZone: http://localhost:8761/eureka
  #instance:
    #prefer-ip-address: true

#management:
  #endpoints:
    #web:
      #exposure:
        #include: '*'