server:
  port: 0
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tarifas_especiales_db
    username: postgres
    password: Admin
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka