---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pg-init-tarifas-sql
  namespace: kartingrm
data:
  init-tarifas.sql: |
    CREATE TABLE IF NOT EXISTS tarifas (
                                           id           SERIAL PRIMARY KEY,
                                           tipo_dia     INT NOT NULL,        -- 0: NORMAL, 1: FINDE, 2: FERIADO
                                           tipo_reserva INT NOT NULL,        -- 0: VUELTAS_10, 1: VUELTAS_15, 2: VUELTAS_20
                                           valor        INT NOT NULL,
                                           CONSTRAINT unique_tarifa UNIQUE (tipo_dia, tipo_reserva)
        );
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-tarifa-reserva-deployment
  namespace: kartingrm
  labels:
    app: db-tarifa-reserva-deployment
    tier: database
spec:
  selector:
    matchLabels:
      app: db-tarifa-reserva-deployment
      tier: database
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: db-tarifa-reserva-deployment
        tier: database
    spec:
      containers:
        - name: db-tarifa-reserva
          image: postgres:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_PASSWORD
              #IMPORTANTE QUE ESTA VARIABLE DE ENTORNO ES LA QUE CREA LA DATABASE NO EL CONFIGMAP XD
            - name: POSTGRES_DB
              value: "tarifareservadb"

          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: db-tarifa-reserva-data

            - mountPath: /docker-entrypoint-initdb.d
              name: init-sql
      volumes:
        - name: db-tarifa-reserva-data
          persistentVolumeClaim:
            claimName: db-tarifa-reserva-pvc

        - name: init-sql
          configMap:
            name: pg-init-tarifas-sql
            items:
              - key: init-tarifas.sql
                path: init-tarifas.sql
---
apiVersion: v1
kind: Service
metadata:
  name: db-tarifareserva-service
  namespace: kartingrm
  labels:
    app: db-tarifareserva-service
    tier: database
spec:
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: db-tarifa-reserva-deployment
    tier: database
  type: ClusterIP
